services:
  - type: web
    name: gau-rakshak-foundation
    env: node
    rootDir: backend      # backend folder
    buildCommand: |
      npm install
      cd ../frontend && npm install && npm run build
      cd ../backend
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REACT_APP_STRIPE_PUBLIC_KEY
        sync: false
      - key: REACT_APP_API_URL
        sync: false
